### ISSUE TITLE
Warpedlmm does not work with latest fastlmm

### ISSUE THREAD

**Issue by edm1** [MicrosoftGenomics/WarpedLMM#2]
```
Traceback (most recent call last):
  File "/panfs/panasas01/sscm/em13383/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/panfs/panasas01/sscm/em13383/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/panfs/panasas01/sscm/em13383/anaconda/lib/python2.7/site-packages/warpedlmm/__main__.py", line 45, in <module>
    snp_data, pheno, covar, X, Y, K = util.load_data(options.snp_file, options.phenotype_file, options.covariates)
  File "/panfs/panasas01/sscm/em13383/anaconda/lib/python2.7/site-packages/warpedlmm/util/util.py", line 12, in load_data
    pheno = plink.loadPhen(pheno_file)
AttributeError: 'module' object has no attribute 'loadPhen'

```
It appears the latest FaST-LMM's `fastlmm.pyplink.plink` module doesn't have the `loadPhen` function anymore.

**Comment by edm1** [comment]
Actually, lots has changed with the newer FaST-LMM. Warpedlmm requires fastlmm=0.2.1 and is broken with the latest version.

As a temporary work-around
```
pip uninstall fastlmm
pip install -I fastlmm==0.2.1
```

**Comment by nfusi** [comment]
Thanks for the report and the workaround. I'm working on changing the code such that it can work with the new fastlmm/pysnptools. In the meanwhile, I've turned on Travis (continuous integration) so that it will be easier to catch this kind of bug in the future.

**Comment by nfusi** [comment]
It should work now.
